// <auto-generated />
namespace Saphira.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class BuildPersonTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BuildPersonTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201704050135439_BuildPersonTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
